### ISSUE TITLE
Enable AVX512VL, use it in yescrypt's Salsa20

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5691]
We need AVX512VL's XOP-like bit rotates for faster Salsa20 in yescrypt. This doesn't affect native yescrypt's speed much, but it does provide great speedup for scrypt (by up to a third in my quick tests) - which is what we currently use this code for.

This is a trivial change to `yescrypt-opt.c`, but that intrinsic fails to compile (at least with gcc 11 for me) until we add `-mavx512vl`. So we have to check specifically for `__AVX512VL__` and enable that specific option. Our current `-mavx512bw` is not enough.

@magnumripper Maybe you can take care of the autoconf stuff for this? I'd appreciate that.

```diff
+++ b/src/yescrypt/yescrypt-opt.c
@@ -74,6 +74,8 @@
 #include <emmintrin.h>
 #ifdef __XOP__
 #include <x86intrin.h>
+#elif defined(__AVX512VL__)
+#include <immintrin.h>
 #endif
 #elif defined(__SSE__)
 #include <xmmintrin.h>
@@ -167,6 +169,9 @@ static inline void salsa20_simd_unshuffle(const salsa20_blk_t *Bin,
 #ifdef __XOP__
 #define ARX(out, in1, in2, s) \
        out = _mm_xor_si128(out, _mm_roti_epi32(_mm_add_epi32(in1, in2), s));
+#elif defined(__AVX512VL__)
+#define ARX(out, in1, in2, s) \
+       out = _mm_xor_si128(out, _mm_rol_epi32(_mm_add_epi32(in1, in2), s));
 #else
 #define ARX(out, in1, in2, s) { \
        __m128i tmp = _mm_add_epi32(in1, in2); \
```

**Comment by solardiz** [comment]
Apparently, BW and VL were introduced at the same time, so we probably don't need a different CPU fallback binary nor a different build in @claudioandre-br's packaging. It will be the same BW build we already have.

However, in that build for correctness we _may_ choose to require also the additional CPUID bit (I guess there's one, I haven't checked) corresponding to VL. And we could adjust the "Sorry" message to mention that both BW and VL are required. If we do any of this, I think it should be separate commit(s) from mere enabling of `-mavx512vl`.

**Comment by solardiz** [comment]
> This is a trivial change to `yescrypt-opt.c`

I've just pushed this change (after having tested it in my fork of the repo). It actually makes a difference already in `./configure --enable-native-march` builds.

**Comment by solardiz** [comment]
We could also consider enabling DQ at the same time since it was also introduced at the same time. Maybe the compiler can make some use of it in some places (can make two builds and check).

**Comment by ghost** [comment]
I find the below interesting (because the binary is still basically BW at this right moment).

```sh
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
checking for AVX512BW + AVX512VL... yes
[...]

Target CPU ......................................... x86_64 AVX512(BW+VL), 64-bit LE
Target OS .......................................... linux-gnu
[...]

Build: linux-gnu 64-bit x86_64 AVX512(BW+VL) AC OMP
SIMD: AVX512BW, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
AES hardware acceleration: AES-NI
CPU tests: AVX512BW
$JOHN is ../run/
```

Makefile:
```sh
CFLAGS_MAIN = -DAC_BUILT -DJOHN_AVX512BW -DJOHN_AVX512VL  $(CFLAGSX)
CFLAGS = -DAC_BUILT -mavx512bw -mavx512vl  -maes -mpclmul -DJOHN_AVX512BW -DJOHN_AVX512VL  $(CFLAGSX)
ASFLAGS = -DAC_BUILT  -DARCH_LITTLE_ENDIAN=1  -mavx512bw -mavx512vl  -maes -mpclmul -DJOHN_AVX512BW -DJOHN_AVX512VL  -c -fopenmp  
```

In the example, a `BW` CPU without `VL` (or anything else) will continue to work fine.

The `SIMD`/`CPU tests` field is still wrong. What should be in `CPU_req_name`?

*******

On a second thougth, only the affected formats should say `AVX512VL`. So the SIMD field is correct as it stands.
* What should be in `CPU_req_name`?

**Comment by solardiz** [comment]
> I find the below interesting

Is this for some patch you prepared, but don't show yet?

> (because the binary is still basically BW at this right moment).

Why is it? At least in yescrypt, we now actually use VL when the macro is defined.

> checking for AVX2... yes
> checking for AVX512F... yes
> checking for AVX512BW... yes
> checking for AVX512BW + AVX512VL... yes

BTW, there's room for `configure` running time optimization here - start by checking AVX512BW+VL and if it's present no need to check for anything else (AVX512F and AVX2 are implied). If not, check AVX512F (and AVX2 is implied). If that is also missing, check AVX2. (I think no need to check for BW alone as no such CPUs are currently known to exist.)

> Target CPU ......................................... x86_64 AVX512(BW+VL), 64-bit LE

We could maybe continue to call it just AVX512BW here, but know that we're also checking/enabling VL (and maybe also DQ). Ditto in fallback binary naming.

The one place where we actually report VL is `ALGORITHM_NAME` where we use it.

> What should be in `CPU_req_name`?

Like I wrote above, for the "Sorry" line, which I think is what you mean here, we should include exactly what we're checking. If we check CPUID bits for BW+VL+DQ, then we should mention all 3 in there.

In other words, we can use the shortcut name of just BW where it doesn't matter much, but if someone actually can't run the program because features are missing we should not use a shortcut.

**Comment by ghost** [comment]
## Is this?

Optimization:
```sh
checking for AVX... yes
checking for XOP... no
checking for AVX2... yes
checking for AVX512BW + AVX512VL... yes
checking if gcc supports -maes -mpclmul... yes

```

CPU:
```sh
Target CPU ......................................... x86_64 AVX512BW, 64-bit LE
Target OS .......................................... linux-gnu

```

Binary:
```sh
Version: 1.9.0-jumbo-1+bleeding-0c8f12a2a1 2025-03-09 20:00:09 -0300
Build: linux-gnu 64-bit x86_64 AVX512(BW+VL) AC OMP
SIMD: AVX512BW, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
AES hardware acceleration: AES-NI
CPU tests: AVX512(BW+VL)
```

Tests:
```sh
Will run 2 OpenMP threads
Testing: crypt, generic crypt(3) [?/64]... (2xOMP) PASS
Testing: descrypt, traditional crypt(3) [DES 512/512 AVX512F]... (2xOMP) PASS
Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX512VL]... (2xOMP) PASS
Testing: django-scrypt [Salsa20/8 128/128 AVX512VL]... (2xOMP) PASS
Testing: sha1crypt, NetBSD's sha1crypt [PBKDF1-SHA1 512/512 AVX512BW 16x]... (2xOMP) PASS
Testing: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 512/512 AVX512BW 16x]... (2xOMP) PASS
Testing: sha512crypt, crypt(3) $6$ (rounds=5000) [SHA512 512/512 AVX512BW 8x]... (2xOMP) PASS
All 7 formats passed self-tests```

**Comment by solardiz** [comment]
> Optimization:
> 
> checking for AVX... yes
> checking for XOP... no
> checking for AVX2... yes
> checking for AVX512BW + AVX512VL... yes
> checking if gcc supports -maes -mpclmul... yes

This is OK, but not as optimized as I had meant. I'd expect just one line:

```
checking for AVX512BW + AVX512VL... yes
```

and nothing else if it's a `yes` there, or otherwise:

```
checking for AVX512BW + AVX512VL... no
checking for AVX2... yes
```

or otherwise:

```
checking for AVX512BW + AVX512VL... no
checking for AVX2... no
checking for XOP... yes
```

or otherwise:

```
checking for AVX512BW + AVX512VL... no
checking for AVX2... no
checking for XOP... no
checking for AVX... yes
```

> CPU:
> 
> Target CPU ......................................... x86_64 AVX512BW, 64-bit LE
> Target OS .......................................... linux-gnu

This is like I meant, thanks!

> Binary:
> 
> Version: 1.9.0-jumbo-1+bleeding-0c8f12a2a1 2025-03-09 20:00:09 -0300
> Build: linux-gnu 64-bit x86_64 AVX512(BW+VL) AC OMP
> SIMD: AVX512BW, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
> AES hardware acceleration: AES-NI
> CPU tests: AVX512(BW+VL)

This is OK.

> Tests:
> 
> Will run 2 OpenMP threads
> Testing: crypt, generic crypt(3) [?/64]... (2xOMP) PASS
> Testing: descrypt, traditional crypt(3) [DES 512/512 AVX512F]... (2xOMP) PASS
> Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX512VL]... (2xOMP) PASS
> Testing: django-scrypt [Salsa20/8 128/128 AVX512VL]... (2xOMP) PASS
> Testing: sha1crypt, NetBSD's sha1crypt [PBKDF1-SHA1 512/512 AVX512BW 16x]... (2xOMP) PASS
> Testing: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 512/512 AVX512BW 16x]... (2xOMP) PASS
> Testing: sha512crypt, crypt(3) $6$ (rounds=5000) [SHA512 512/512 AVX512BW 8x]... (2xOMP) PASS
> All 7 formats passed self-tests

Looks correct.

On a related note, we probably misreport AVX512BW in place of AVX512F for MD4 and MD5. Looks like in `pseudo_intrinsics.h` we only use BW for endianness swapping, which I guess we only need for `SHA*`. But let's not get distracted to fixing that just yet.

**Comment by ghost** [comment]
The optimization is invasive. I'll put it aside for a while. Anyway:

Instead of:

```sh
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for SSE4.2... yes
checking for AVX... yes
checking for XOP... no
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
checking for AVX512BW + AVX512VL... no
```

Use:
```sh
checking for AVX512BW + AVX512VL... no
checking for AVX512F... no  <<============================
checking for AVX2... no
checking for XOP... no
checking for AVX... no
checking for SSE4.2... no
checking for SSE4.1... no
checking for SSSE3... no
checking for SSE2... no
checking for MMX... yes
```
*****

The patch:
* still missing the proper C detection [1];
* full CI test pending.

[0001-autotools-add-AVX512VL-detection.PATCH](https://github.com/user-attachments/files/19153631/0001-autotools-add-AVX512VL-detection.PATCH)

[1] Something to replace:
```C
int main(){__m512i t, t1;*((long long*)&t)=1;t1=t;t=_mm512_mul_epi32(t1,t);if((*(long long*)&t)==88)printf(".");exit(0);}
```

**Comment by solardiz** [comment]
> We could also consider enabling DQ at the same time since it was also introduced at the same time. Maybe the compiler can make some use of it in some places (can make two builds and check).

Comparing 3 builds (same gcc 11) - BW, BW+VL, BW+VL+DQ - I see that VL adds use of these instruction mnemonics (for any register width, so without VL we didn't use these mnemonics at all), as seen in `objdump -d john`:

```diff
 vpmaxsd
+vpmaxsq
 vpmaxud
+vpmaxuq
 vpminsd
+vpminsq
 vpminud
+vpminuq

 vpxor
 vpxord
+vpxorq
```

(I preserved some nearby lines of `diff` output to show related mnemonics we were using before.)

If the comparison is limited to non-ZMM registers, it adds use of more mnemonics:

```diff
 vmovaps
 vmovd
 vmovdqa
+vmovdqa32
+vmovdqa64
 vmovdqu
+vmovdqu64
 vmovq
 vmovsd

 vpmaxsd
+vpmaxsq
 vpmaxud
+vpmaxuq
 vpminsd
+vpminsq
 vpminud
+vpminuq

+vprold
+vprord

+vpternlogd

 vpxor
+vpxorq
```

There are thousands of uses of `vmovdqa32` and `vmovdqa64`. I guess those element size qualifiers are supposed to speed things up in some cases or on some CPUs?

There's a hundred of uses of `vpxorq`, but still two thousand of simple `vpxor`. Again, I wonder if the element size qualifier is supposed to help speeds somewhere, and I wonder why we aren't seeing similar for other bitwise operations.

There's just one use of `vpternlogd` on non-ZMM, and this one is changed from ZMM to XMM:

```diff
-  52ef9e:	62 f3 75 48 25 c9 55 	vpternlogd $0x55,%zmm1,%zmm1,%zmm1
+  52ea9e:	62 f3 75 08 25 c9 55 	vpternlogd $0x55,%xmm1,%xmm1,%xmm1
```

DQ further adds a few:

```diff
+kmovb
 kmovd
 kmovq
 kmovw
 kord
+kortestb
 kortestd
 kortestq
+kxnorb
 kxnorw
+kxorb
 kxord
-kxorw
```

Code size decreases slightly as more instruction set extensions are enabled:

```
$ size john-bw john-vl john-dq
   text	   data	    bss	    dec	    hex	filename
5646604	 615652	6345984	12608240	 c062f0	john-bw
5645780	 615652	6345984	12607416	 c05fb8	john-vl
5645572	 615652	6345984	12607208	 c05ee8	john-dq
```

I think we may want to add DQ to the same builds where we have BW+VL. So only have BW+VL+DQ and not BW+VL nor BW alone.

**Comment by solardiz** [comment]
> The optimization is invasive. I'll put it aside for a while.

Yes, changing the order of checks and making them inter-dependent is invasive. I agree with putting it aside. Definitely shouldn't be in the same commit with addition of VL.

> still missing the proper C detection [1];

By "proper" do you mean without breaking strict aliasing rules? Yes, we should fix these test programs eventually, although I think for x86 intrinsics in particular there are stronger aliasing guarantees than C normally provides.

> [0001-autotools-add-AVX512VL-detection.PATCH](https://github.com/user-attachments/files/19153631/0001-autotools-add-AVX512VL-detection.PATCH)

This looks ready for a PR for _just_ adding VL (no optimization yet, nor DQ yet). That's fine and valuable on its own. Thank you!

**Comment by ghost** [comment]
> By "proper" do you mean without breaking strict aliasing rules? 

No. I mean I copied the code from the AVX512F section. It is NOT detecting `VL` yet.

**Comment by ghost** [comment]
Changing the order of checks is REALY invasive and requires OLD hardware to run some tests.

I can test it right up to `AVX2`:

A simple `./configure`:
```sh
configure: Testing build host's native CPU features
checking for AVX512BW + AVX512VL... no
checking for AVX512F... no
checking for AVX2... yes
```

It would be nice if we had SSE2 and XOP to run tests. 

[0001-optimization.PATCH](https://github.com/user-attachments/files/19154159/0001-optimization.PATCH)  => WIP: only the if part was edited. The else part is still missing.

**Comment by solardiz** [comment]
> No. I mean I copied the code from the AVX512F section. It is NOT detecting `VL` yet.

Oh, indeed. For a quick fix, I suggest we use the same intrinsic I added in `yescrypt-opt.c`.

> Changing the order of checks is REALY invasive and requires OLD hardware to run some tests.

Let's postpone this. There are lots of other things for us to simplify in our configure checks anyway.

**Comment by solardiz** [comment]
@claudioandre-br has completed this issue via #5694, so I'm closing it.

The future AVX10/256 may be similar to AVX512VL without AVX512F/BW/DQ, so we may revisit this aspect later (open a separate issue for it).

**Comment by magnumripper** [comment]
> > Changing the order of checks is REALY invasive and requires OLD hardware to run some tests.
> 
> Let's postpone this. There are lots of other things for us to simplify in our configure checks anyway.

It's only invasive in terms of patch size, no? Doing it should be super trivial, literally just reorder the tests (but place XOP first, only then AVX512xx). Or is it more invasive in some way I miss here?

**Comment by ghost** [comment]
> It's only invasive in terms of patch size, no?

Invasive due to the size of the patch and the number of changes. But it's actually very simple.

**Comment by magnumripper** [comment]
> literally just reorder the tests (but place XOP first, only then AVX512xx)

This isn't entirely correct though. The logic for aborting tests needs to be reversed so a fail generally leads to checking next lower, and a pass can stop the checking.
